"""
Evidence Requirements Mapping for Governance Stages.
Defines required evidence artifacts and fields required before any state advancement can occur.
"""
from __future__ import annotations

from typing import Dict, List
from .state_machine import PromotionState


STATE_EVIDENCE_REQUIREMENTS: Dict[PromotionState, List[str]] = {
    PromotionState.EXPLORATORY: ["RESEARCH_QUESTION", "HYPOTHESIS"],
    PromotionState.DISCOVERED: ["RESEARCH_QUESTION", "HYPOTHESIS", "DATASET_MANIFEST", "PIT_DATA", "ALPHA_AST"],
    PromotionState.OOS_VALIDATED: [
        "RESEARCH_QUESTION", "HYPOTHESIS", "DATASET_MANIFEST", "PIT_DATA", "ALPHA_AST",
        "TRIAL_REGISTRY", "VALIDATION_RESULT",
    ],
    PromotionState.STATISTICALLY_VALIDATED: [
        "RESEARCH_QUESTION", "HYPOTHESIS", "DATASET_MANIFEST", "PIT_DATA", "ALPHA_AST",
        "TRIAL_REGISTRY", "VALIDATION_RESULT", "STATISTICAL_TESTS",
    ],
    PromotionState.COST_VALIDATED: [
        "RESEARCH_QUESTION", "HYPOTHESIS", "DATASET_MANIFEST", "PIT_DATA", "ALPHA_AST",
        "TRIAL_REGISTRY", "VALIDATION_RESULT", "STATISTICAL_TESTS", "EXECUTION_RESULT",
    ],
    PromotionState.CAPACITY_VALIDATED: [
        "RESEARCH_QUESTION", "HYPOTHESIS", "DATASET_MANIFEST", "PIT_DATA", "ALPHA_AST",
        "TRIAL_REGISTRY", "VALIDATION_RESULT", "STATISTICAL_TESTS", "EXECUTION_RESULT",
    ],
    PromotionState.RISK_VALIDATED: [
        "RESEARCH_QUESTION", "HYPOTHESIS", "DATASET_MANIFEST", "PIT_DATA", "ALPHA_AST",
        "TRIAL_REGISTRY", "VALIDATION_RESULT", "STATISTICAL_TESTS", "EXECUTION_RESULT",
        "PORTFOLIO_RESULT", "RISK_RESULT",
    ],
    PromotionState.PAPER: [
        "RESEARCH_QUESTION", "HYPOTHESIS", "DATASET_MANIFEST", "PIT_DATA", "ALPHA_AST",
        "TRIAL_REGISTRY", "VALIDATION_RESULT", "STATISTICAL_TESTS", "EXECUTION_RESULT",
        "PORTFOLIO_RESULT", "RISK_RESULT", "FALSIFICATION",
    ],
    PromotionState.SHADOW: [
        "RESEARCH_QUESTION", "HYPOTHESIS", "DATASET_MANIFEST", "PIT_DATA", "ALPHA_AST",
        "TRIAL_REGISTRY", "VALIDATION_RESULT", "STATISTICAL_TESTS", "EXECUTION_RESULT",
        "PORTFOLIO_RESULT", "RISK_RESULT", "FALSIFICATION", "REPRODUCTION_RECORD",
    ],
    PromotionState.PRODUCTION_CANDIDATE: [
        "RESEARCH_QUESTION", "HYPOTHESIS", "DATASET_MANIFEST", "PIT_DATA", "ALPHA_AST",
        "TRIAL_REGISTRY", "VALIDATION_RESULT", "STATISTICAL_TESTS", "EXECUTION_RESULT",
        "PORTFOLIO_RESULT", "RISK_RESULT", "FALSIFICATION", "REPRODUCTION_RECORD", "FINAL_EVIDENCE",
    ],
    PromotionState.APPROVED: [
        "RESEARCH_QUESTION", "HYPOTHESIS", "DATASET_MANIFEST", "PIT_DATA", "ALPHA_AST",
        "TRIAL_REGISTRY", "VALIDATION_RESULT", "STATISTICAL_TESTS", "EXECUTION_RESULT",
        "PORTFOLIO_RESULT", "RISK_RESULT", "FALSIFICATION", "REPRODUCTION_RECORD", "FINAL_EVIDENCE",
    ],
}


def get_required_stages_for_state(target_state: PromotionState) -> List[str]:
    """Retrieve all prerequisite evidence stages required to reach target_state."""
    return STATE_EVIDENCE_REQUIREMENTS.get(target_state, [])
